# Generated by Django 5.0.4 on 2024-05-04 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_consulta_anotacoes_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('tempo_espera', models.PositiveSmallIntegerField()),
                ('satisfacao', models.PositiveSmallIntegerField()),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pacientes.consulta')),
            ],
            options={
                'verbose_name_plural': 'Avaliações',
            },
        ),
    ]
