# Generated by Django 5.0.4 on 2024-05-05 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_avaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='consulta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='pacientes.consulta'),
        ),
    ]
