# Generated by Django 5.0.4 on 2024-05-05 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_alter_avaliacao_consulta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='data',
        ),
    ]
