# Generated by Django 5.0.4 on 2024-05-23 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_analise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='crm',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
